name: Deploy to EC2 IIS Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Zip source files
      run: |
        zip -r deploy.zip . -x "*.git*" "*.github*"

    - name: Upload zip to EC2 (requires OpenSSH or SCP)
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.IIS_SERVER }}
        username: ${{ secrets.IIS_USERNAME }}
        password: ${{ secrets.IIS_PASSWORD }}
        port: 5986
        source: deploy.zip
        target: C:\Users\${{ secrets.IIS_USERNAME }}

    - name: Unzip and deploy on IIS (via WinRM)
      uses: azure/winrm@v1
      with:
        hostname: ${{ secrets.IIS_SERVER }}
        username: ${{ secrets.IIS_USERNAME }}
        password: ${{ secrets.IIS_PASSWORD }}
        port: 5986
        protocol: https
        commands: |
          Remove-Item -Recurse -Force C:\inetpub\wwwroot\*
          Expand-Archive -Path C:\Users\${{ secrets.IIS_USERNAME }}\deploy.zip -DestinationPath C:\inetpub\wwwroot
