name: Deploy Hello World to Windows IIS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload and deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IIS_SERVER }}
        username: ${{ secrets.IIS_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          powershell -Command "
            Remove-Item -Path 'C:\inetpub\wwwroot\*' -Recurse -Force;
            New-Item -Path 'C:\inetpub\wwwroot\index.html' -ItemType File -Force;
            Set-Content -Path 'C:\inetpub\wwwroot\index.html' -Value @'
            <!DOCTYPE html>
            <html><head><title>Hello</title></head><body><h1>Hello World from GitHub Actions!</h1></body></html>
            '@
          "
